name: Build Documentation

on:
  pull_request:
    paths:
      - 'docs/**' # Trigger on changes to the docs directory
  workflow_dispatch: # Allow manual triggering of the workflow from the Actions tab

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v1

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Install Graphviz and LaTeX packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y graphviz
        sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - name: Check for missing needs links
      run: |
        cd docs
        sphinx-build -b linkcheck -q source build 2>&1 | \
          grep '\[needs\]' | \
          sed 's/^/\n.. todo:: /' >> source/overview.rst
      continue-on-error: true

    - name: Build Sphinx documentation
      run: |
        cd docs
        make latexpdf
        make html

    - name: Delete existing artifacts
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts || echo "No artifacts to delete"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: req-mgmt.pdf
        path: docs/build/latex/req-mgmt.pdf

    - name: Upload HTML artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages